### ISSUE TITLE
Failed code audit

### ISSUE THREAD

**Issue by hirefl** [GenesisVision/web-client#1672]
I am in the process of auditing the code. Latest stable NodeJS v12.18.3 and Yarn 1.22.5 all running under Windows 10. 
`git clone https://github.com/GenesisVision/web-client`
In the web-client dir i ran
`yarn` and in packages -> social-trader i ran
`yarn build` successfully and `yarn start`
with chrome i navigated to localhost:3000 all templates compile successfully, but when i try to navigate on the website for example "Funds", i receive `Server Error
Server error occurred. Please try again later or contact the support department.` I suppose a DB has to be initialized. I did not find any relevant .env or documentation for this community funded project. Please advise or share relevant information to audit. Thank you.

**Comment by pavelzubov** [comment]
Write path to REACT_APP_API_URL in .env
