### ISSUE TITLE
Missing environment variables

### ISSUE THREAD

**Issue by hirefl** [GenesisVision/web-client#1675]
the project is missing more .env variables for database etc.

https://github.com/GenesisVision/web-client/issues/1672

i ran `npm run generate-api` with error `Error: Could not find or load main class io.swagger.codegen.v3.cli.SwaggerCodegen`

do you know where i can find them please? i think all of this is related to the missing environment variables. Please advise. Thanks

**Comment by pavelzubov** [comment]
Write path to API_URL in .env
